local quest = {
	name = "Bloody Tusks Quest",
	startStorageId = Storage.Quest.U15_10.BloodyTusks.Questline,
	startStorageValue = 1,
	missions = {
		[1] = {
			name = "Into the grave",
			storageId = Storage.Quest.U15_10.BloodyTusks.IntoTheGrave,
			missionId = 10461,
			startValue = 1,
			endValue = 2,
			description = "Find the strange grave the bat was talking about. It can't be that far.",
		},
		[2] = {
			name = "Through the mist",
			storageId = Storage.Quest.U15_10.BloodyTusks.ThroughTheMist,
			missionId = 10462,
			startValue = 1,
			endValue = 2,
			description = "You were sent to investigate a looming threat of some kind of orcish vampire and his offspring. Locate the Norcferatu fortress in Vengoth and find a way to enter it.",
		},
		[3] = {
			name = "The wrath of the ancestors",
			storageId = Storage.Quest.U15_10.BloodyTusks.TheWrathOfTheAncestorst,
			missionId = 10463,
			startValue = 1,
			endValue = 2,
			description = "You first have to gain the assistance of the angered spirits of the orcish ancestors. Find the ancient burial cave and find a way to contact and appease them.",
		},
		[4] = {
			name = "Dance of death",
			storageId = Storage.Quest.U15_10.BloodyTusks.DanceOfDeath,
			missionId = 10464,
			startValue = 1,
			endValue = 2,
			description = "Apeease the Norcferatu ancestors by participating in the ancient orcish ritual dance. Dance the dance of the red full moon and gain their approval.",
		},
		[5] = {
			name = "The next step",
			storageId = Storage.Quest.U15_10.BloodyTusks.TheNextStep,
			missionId = 10465,
			startValue = 1,
			endValue = 2,
			description = "With the ancestor spirits on your side, it's time to learn hat to do next to gain entrance to Vladdrukhs underground lair. Report back to Anaztassja.",
		},
		[6] = {
			name = "Bloodbath",
			storageId = Storage.Quest.U15_10.BloodyTusks.Bloodbath,
			missionId = 10466,
			startValue = 1,
			endValue = 2,
			description = "To fool the magic wards of the fortress, you must first befoul yourself. Gain entrance to the bloodbath and let the Norcferatu's tainted blood seep into your flesh.",
		},
		[7] = {
			name = "Well prepared",
			storageId = Storage.Quest.U15_10.BloodyTusks.WellPrepared,
			missionId = 10467,
			startValue = 1,
			endValue = 2,
			description = "You have finished the necesary preparations. Talk to Anaztasja about entering the lower levels.",
		},
		[8] = {
			name = "Breaking in",
			storageId = Storage.Quest.U15_10.BloodyTusks.BreakingIn,
			missionId = 10468,
			startValue = 1,
			endValue = 2,
			description = "Gain acess to the Vlarukh's underground dungeon. Use orcish talismans to lure a possessed Behemoth to the gate.",
		},
		[9] = {
			name = "Into the vampire's lair",
			storageId = Storage.Quest.U15_10.BloodyTusks.IntoTheVampiresLair,
			missionId = 10469,
			startValue = 1,
			endValue = 2,
			description = "Seek out Anaztassja, hidden deep within the dungeon levels of Blood Tusk Keep. She will know what must be done next.",
		},
		[10] = {
			name = "The blood ritual",
			storageId = Storage.Quest.U15_10.BloodyTusks.TheBloodRitual,
			missionId = 10470,
			startValue = 1,
			endValue = 2,
			description = "Protect Anaztassja while she tries to break the final seals in a magic ritual.",
		},
	},
}

return quest
