#!/usr/bin/env python3
"""Upload compressed backups to Google Cloud Storage using a service account."""
from __future__ import annotations

import argparse
import logging
import os
import pathlib
import sys
from typing import Optional


def parse_args() -> argparse.Namespace:
    env = os.environ
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("backup_file", help="Path to the backup file generated by the server.")
    parser.add_argument(
        "--gcs-bucket",
        default=env.get("BACKUP_GCS_BUCKET"),
        help="Name of the Google Cloud Storage bucket (required).",
    )
    parser.add_argument(
        "--gcs-prefix",
        default=env.get("BACKUP_GCS_PREFIX", "database-backups"),
        help="Object prefix/folder inside the bucket (default: database-backups).",
    )
    parser.add_argument(
        "--gcs-credentials",
        default=env.get("BACKUP_GCS_CREDENTIALS"),
        help="Path to the service account JSON credentials used for authentication.",
    )
    parser.add_argument(
        "--gcs-storage-class",
        default=env.get("BACKUP_GCS_STORAGE_CLASS", "STANDARD"),
        help="Storage class for new objects (e.g., STANDARD, NEARLINE, COLDLINE).",
    )
    parser.add_argument(
        "--gcs-kms-key",
        default=env.get("BACKUP_GCS_KMS_KEY"),
        help="Optional Cloud KMS key resource name for server-side encryption.",
    )
    parser.add_argument(
        "--gcs-cache-control",
        default=env.get("BACKUP_GCS_CACHE_CONTROL"),
        help="Optional Cache-Control header set on the object.",
    )
    parser.add_argument(
        "--gcs-content-type",
        default=env.get("BACKUP_GCS_CONTENT_TYPE", "application/gzip"),
        help="MIME type reported to GCS (default: application/gzip).",
    )
    parser.add_argument(
        "--delete-local",
        action="store_true",
        help="Delete the local file after a successful upload.",
    )
    parser.add_argument(
        "--log-level",
        default=env.get("BACKUP_UPLOAD_LOG_LEVEL", "INFO"),
        choices=("DEBUG", "INFO", "WARNING", "ERROR"),
        help="Verbosity for stdout logging.",
    )
    return parser.parse_args()


def upload_to_gcs(
    file_path: pathlib.Path,
    bucket_name: Optional[str],
    prefix: str,
    credentials_path: Optional[str],
    storage_class: Optional[str],
    kms_key: Optional[str],
    cache_control: Optional[str],
    content_type: Optional[str],
) -> str:
    try:
        from google.api_core.exceptions import GoogleAPIError, NotFound
        from google.cloud import storage
    except ImportError as exc:  # pragma: no cover - validation path
        raise RuntimeError(
            "google-cloud-storage is required. Install it with 'pip install google-cloud-storage'."
        ) from exc

    if not bucket_name:
        raise ValueError("--gcs-bucket is required to upload backups.")

    if credentials_path:
        client = storage.Client.from_service_account_json(credentials_path)
    else:
        client = storage.Client()

    try:
        bucket = client.get_bucket(bucket_name)
    except NotFound as exc:
        raise RuntimeError(f"Bucket '{bucket_name}' was not found or is not accessible: {exc}") from exc

    normalized_prefix = prefix.strip("/") if prefix else ""
    object_name = f"{normalized_prefix}/{file_path.name}" if normalized_prefix else file_path.name
    blob = bucket.blob(object_name)

    if storage_class:
        blob.storage_class = storage_class
    if kms_key:
        blob.kms_key_name = kms_key
    if cache_control:
        blob.cache_control = cache_control

    upload_kwargs = {}
    if content_type:
        upload_kwargs["content_type"] = content_type

    logging.info("Uploading %s to gs://%s/%s", file_path, bucket_name, object_name)
    try:
        blob.upload_from_filename(str(file_path), **upload_kwargs)
    except GoogleAPIError as exc:
        raise RuntimeError(f"Failed to upload backup to Google Cloud Storage: {exc}") from exc

    logging.info("Upload finished (size=%s bytes).", file_path.stat().st_size)
    return f"gs://{bucket_name}/{object_name}"


def main() -> int:
    args = parse_args()
    logging.basicConfig(level=getattr(logging, args.log_level.upper()), format="%(levelname)s: %(message)s")
    file_path = pathlib.Path(args.backup_file).expanduser().resolve()
    if not file_path.exists():
        raise FileNotFoundError(f"Backup file does not exist: {file_path}")

    gcs_uri = upload_to_gcs(
        file_path,
        args.gcs_bucket,
        args.gcs_prefix,
        args.gcs_credentials,
        args.gcs_storage_class,
        args.gcs_kms_key,
        args.gcs_cache_control,
        args.gcs_content_type,
    )

    if args.delete_local:
        logging.info("Deleting local backup after successful upload: %s", file_path)
        try:
            file_path.unlink()
        except FileNotFoundError:
            logging.warning("Local backup was already removed: %s", file_path)

    logging.info("Backup upload completed successfully: %s", gcs_uri)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # pragma: no cover - CLI entry point
        logging.error("%s", exc)
        sys.exit(1)
